# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'agree.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(700, 500))
        Dialog.setMaximumSize(QtCore.QSize(700, 500))
        Dialog.setStyleSheet("QDialog{\n"
"    background:#ffffff\n"
"}")
        self.btn_continue = QtWidgets.QPushButton(Dialog)
        self.btn_continue.setGeometry(QtCore.QRect(450, 450, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.btn_continue.setFont(font)
        self.btn_continue.setObjectName("btn_continue")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 70, 700, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setStyleSheet("background:#26a9e1")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lb_logo = QtWidgets.QLabel(Dialog)
        self.lb_logo.setGeometry(QtCore.QRect(0, 0, 700, 70))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lb_logo.setFont(font)
        self.lb_logo.setStyleSheet("background:#ffffff")
        self.lb_logo.setText("")
        self.lb_logo.setObjectName("lb_logo")
        self.btn_close = QtWidgets.QPushButton(Dialog)
        self.btn_close.setGeometry(QtCore.QRect(140, 450, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.btn_close.setFont(font)
        self.btn_close.setObjectName("btn_close")
        self.cb_agree = QtWidgets.QCheckBox(Dialog)
        self.cb_agree.setGeometry(QtCore.QRect(33, 110, 521, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.cb_agree.setFont(font)
        self.cb_agree.setObjectName("cb_agree")
        self.btn_print = QtWidgets.QPushButton(Dialog)
        self.btn_print.setGeometry(QtCore.QRect(530, 110, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.btn_print.setFont(font)
        self.btn_print.setObjectName("btn_print")
        self.tb_text = QtWidgets.QTextBrowser(Dialog)
        self.tb_text.setGeometry(QtCore.QRect(30, 150, 641, 281))
        self.tb_text.setObjectName("tb_text")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Deactivated Data Engine"))
        self.btn_continue.setText(_translate("Dialog", "Continue"))
        self.btn_close.setText(_translate("Dialog", "Close"))
        self.cb_agree.setText(_translate("Dialog", "I accept the following terms and conditions"))
        self.btn_print.setText(_translate("Dialog", "Print"))
        self.tb_text.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">I am authorized to use the DEA Lookup Downloading Tool on behalf of [company name] a current licensee of DEA Lookup software.  I have read and, on behalf of myself and the licensee, I agree to the terms of the DEA Registration Dataset Data-Use Acknowledgment set forth below (the &quot;DEA Terms&quot;) and authorize DEA Lookup to communicate my agreement to the DEA Terms as part of each automated download of data.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">***</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">DEA REGISTRATION DATASET DATA-USE ACKNOWLEDGMENT</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">The Drug Enforcement Administration is the owner of the DEA Controlled Substances Act Registration Information Database, and the dataset contained within. Access to the DEA Controlled Substances Act Registration Information Database, and the dataset contained within, is limited to those registered with or by application to the Drug Enforcement Administration in order to comply with Federal, State, and local Statutes and Rules.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">The repackaging and/or remarketing of the DEA Controlled Substances Act Registration Information Database, and the dataset contained within, is strictly forbidden without the written consent of the Drug Enforcement Administration.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">By your acknowledgement below, you agree to the following:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1. Information contained within the dataset will only be used for the approved purposes described in the justification described within this application. Intentional misuse of the information contained within the dataset to include: unauthorized distribution, reverse engineering, re-engineering, profit from the sale, or the incorporation in a software system or package, are subject to criminal prosecution.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">2. Agree to protect access to the information to prevent any unauthorized use thereof.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">3. Agree to notify DEA within 24 hours if any provided data is breached and/or disclosed to unauthorized persons.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">4. Agree to protect the information from any further dissemination and/or unauthorized use.</span></p></body></html>"))
