# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(500, 300))
        Dialog.setMaximumSize(QtCore.QSize(500, 300))
        font = QtGui.QFont()
        font.setFamily("Arial")
        Dialog.setFont(font)
        Dialog.setStyleSheet("QDialog{\n"
"    background:#ffffff\n"
"}")
        self.lb_logo = QtWidgets.QLabel(Dialog)
        self.lb_logo.setGeometry(QtCore.QRect(20, 30, 460, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lb_logo.setFont(font)
        self.lb_logo.setStyleSheet("background:#ffffff")
        self.lb_logo.setText("")
        self.lb_logo.setObjectName("lb_logo")
        self.pb_load = QtWidgets.QProgressBar(Dialog)
        self.pb_load.setGeometry(QtCore.QRect(5, 260, 490, 15))
        self.pb_load.setAutoFillBackground(False)
        self.pb_load.setStyleSheet("QProgressBar{\n"
"    border:none;\n"
"    text-align:center;\n"
"}\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color:#8cc540;\n"
"}")
        self.pb_load.setProperty("value", 24)
        self.pb_load.setTextVisible(False)
        self.pb_load.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.pb_load.setFormat("")
        self.pb_load.setObjectName("pb_load")
        self.lb_msg = QtWidgets.QLabel(Dialog)
        self.lb_msg.setGeometry(QtCore.QRect(7, 240, 210, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lb_msg.setFont(font)
        self.lb_msg.setObjectName("lb_msg")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Deactivated Data Engine"))
        self.lb_msg.setText(_translate("Dialog", "Checking server connection ..."))
